import React from 'react';

export default function MechanicMaintenanceEntry() {
  return (
    <div className="border p-4 rounded-lg shadow-sm bg-white">
      <h3 className="text-lg font-semibold mb-3">Maintenance Entry</h3>
      <div className="mb-4">
        <label htmlFor="workDescription" className="block text-sm font-medium text-gray-700 mb-1">Description of Work Done:</label>
        <textarea
          id="workDescription"
          className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
          rows="6"
          placeholder="Enter detailed description of maintenance work..."
        ></textarea>
      </div>
      <div className="mb-4">
        <p className="text-sm font-medium text-gray-700">E-Signature and Verification:</p>
        <div className="bg-gray-100 p-3 rounded-md text-sm text-gray-600">
          [Placeholder for Autogenerated E-signature and FAA Standard Verification]
        </div>
      </div>
      <div className="mb-4">
        <p className="text-sm font-medium text-gray-700">Logbook Integration:</p>
        <div className="bg-gray-100 p-3 rounded-md text-sm text-gray-600">
          [Work completed will be directly integrated into the appropriate aircraft logbook for squawks.]
        </div>
      </div>
      <div className="flex justify-end space-x-2">
        <button className="px-4 py-2 bg-gray-300 text-gray-800 rounded-md hover:bg-gray-400 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2">
          Print / Export
        </button>
        <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2">
          Submit Maintenance Entry
        </button>
      </div>
    </div>
  );
}
